BOX MEALS=>
                                                        {
                                                            id:"26"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32050-0.jpg?ver=1.10"
                                                            name:"All Chicken Box"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹179.00"
                                                            description:"A Box with your favorites! Get 1 pc Hot & Crispy, 2 Hot Wings & 1 Chicken Strip at a deal price"
                                                        }
                                                        {
                                                            id:"27"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32053-0.jpg?ver=1.10"
                                                            name:"Classic Zinger Box"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹299.00"
                                                            description: "A deal for the Tandoori lovers : Get 1 Tandoori Zinger, 2 Hot Wings, 1 Veg Patty & Pepsi"
                                                        }
                                                        {
                                                            id:"28"
                                                            image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32383-0.jpg?ver=1.10"
                                                            name:"Zinger Tandoori Box"
                                                            category: "Non veg"
                                                            serving: ""
                                                            price: "₹299.00"
                                                            description:"A deal for the Tandoori lovers : Get 1 Tandoori Zinger, 2 Hot Wings, 1 Veg Patty & Pepsi"
                                                        }
                                                        {
                                                            id:"29"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-33527-0.jpg?ver=1.10"
                                                            name:"Popcorn Biryani Box"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹329.00"
                                                            description :"Biryani lovers unite : Get 1 Popcorn Biryani Bucket with gravy, 2 Hot Wings & Pepsi"
                                                        }
                                                    
                                                        {
                                                            id:"30"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32055-0.jpg?ver=1.10"
                                                            name:"Veg Zinger Box"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹299.00"
                                                            description : "A deal for the Veg Zinger lovers : Get 1 Veg Zinger, 2 Veg Patties & a Pepsi"
                                                        }
BURGERS=>
                                                    
                                                        {
                                                            id:"31"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-33526-0.jpg?ver=1.10"
                                                            name:"Veg Biryani Box"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹279.00"
                                                            description : "Biryani lovers unite : Get 1 Veg Biryani Bucket with gravy, 1 Veg Patty & a Pepsi"
                                                        }
                                                    
                                                        {
                                                            id:"32"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32576-0.jpg?ver=1.10"
                                                            name:"2 Chicken Krisper Burgers"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹219.00"
                                                            description : "2 delicious chicken value burgers - at only 109 each!"
                                                        }
                                                    
                                                        {
                                                            id:"33"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32573-0.jpg?ver=1.10"
                                                            name:"2 Veg Krisper Burgers"
                                                            category:"Veg"
                                                            serving:""
                                                            price:"₹138.00"
                                                            description : "2 delicious veg value burgers - at only 69 each!"
                                                        }
                                                    
                                                        {
                                                            id:"34"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32578-0.jpg?ver=1.10"
                                                            name:"Chicken & Krispers Combo"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹499.00"
                                                            description : "Save Rs. 50 on this combo of 2 chicken value burgers, 2 pc Hot & Crispy, 2 dips & a chilled Pepsi PET!"
                                                        }
                                                    
                                                        {
                                                            id:"35"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32579-0.jpg?ver=1.10"
                                                            name:"Veg-Non-Veg Krispers Combo"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹349.00"
                                                            description : "Pack of 4 burgers - 2 veg & 2 chicken value burgers at a deal price !"
                                                        }
                                                    
                                                        {
                                                            id:"36"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32230-41486.jpg?ver=1.10"
                                                            name:"Tandoori Zinger Burger"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹180.00"
                                                            description : "Chicken zinger with a delicious tandoori sauce"
                                                        }
                                                    
                                                        {
                                                            id:"37"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32232-0.jpg?ver=1.10"
                                                            name:"Mixed Zinger Doubles"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹309.00"
                                                            description : "Best-seller combo of classic chicken zinger & tandoori zinger"
                                                        }
                                                    
                                                        {
                                                            id:"38"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-30663-40505.jpg?ver=1.10"
                                                            name:"Classic Zinger Burger"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹170.00"
                                                            description : "Signature chicken burger made with a crunchy chicken fillet, veggies & a delicious mayo sauce"
                                                        }
                                                    
                                                        {
                                                            id:"39"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32172-0.jpg?ver=1.10"
                                                            name:"Buddy Meal"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹460.00"
                                                            description : "Share 2 Classic Chicken Zingers & a Medium Popcorn in this delightful combo for 2"
                                                        }
                                                    
                                                        {
                                                            id:"40"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32403-41750.jpg?ver=1.10"
                                                            name:"Veg Zinger Burger"
                                                            category:"Veg"
                                                            serving:""
                                                            price:"₹160.00"
                                                            description : "Signature veg burger with crispy patties, veggies & a tangy sauce"
                                                        }
                                                    
                                                        {
                                                            id:"41"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-32574-0.jpg?ver=1.10"
                                                            name:"2 Veg Krispers Meal"
                                                            category:"Veg"
                                                            serving:""
                                                            price:"₹249.00"
                                                            description : "2 veg value burgers, crispy medium fries & 2 delicious dips at a deal price!"
                                                        }
BEVERAGES=>
                                                        
                                                        {
                                                            id:"73"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-30683-40520.jpg?ver=1.10"
                                                            name:"Pepsi PET"
                                                            category:"Veg"
                                                            serving:""
                                                            price:"₹60.00"
                                                            description : "Pepsi Pet Bottle"
                                                        }
                                                        {
                                                            id:"74"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-31373-41015.jpg?ver=1.10"
                                                            name:"Pepsi Can 330 ml"
                                                            category:"Veg"
                                                            serving:""
                                                            price:"₹60.00"
                                                            description : "Pepsi Can 330 ml"
                                                        }
                                                        {
                                                            id:"75"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-31374-41016.jpg?ver=1.10"
                                                            name:"7UP Can 330 ml"
                                                            category:"Veg"
                                                            serving:""
                                                            price:"₹60.00"
                                                            description : "7UP Can 330 ml"
                                                        }
                                                        {
                                                            id:"76"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-31376-41018.jpg?ver=1.10"
                                                            name:"Pepsi Black Can 330 ml"
                                                            category:"Non veg"
                                                            serving:""
                                                            price:"₹60.00"
                                                            description : "Pepsi Black Can 330 ml"
                                                        }
                                                        {
                                                            id:"77"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-31375-41017.jpg?ver=1.10"
                                                            name:"Mirinda Can 330 ml"
                                                            category:"Veg"
                                                            serving:""
                                                            price:"₹60.00"
                                                            description : "Mirinda Can 330 ml"
                                                        }
                                                        {
                                                            id:"78"
                                                            image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/A-30684-40521.jpg?ver=1.10"
                                                            name:"Red Bull Energy Drink"
                                                            category:"Veg"
                                                            serving:""
                                                            price:"₹160.00"
                                                            description : "Red Bull Energy Drink"
                                                        }
                                                    